packages:
  - apps/*
  - shared/*
  - e2e-tests

catalog:
  # Core dependencies used across multiple apps
  typescript: ^5.8.3
  "@types/node": ^22.15.21
  "@types/chrome": ^0.0.326
  "@types/json-schema": ^7.0.15
  dotenv: 16.5.0
  zod: 3.23.8
  uuid: ^11.1.0
  "json-schema": ^0.4.0

  # MCP packages
  "@modelcontextprotocol/sdk": 1.15.0
  "@mcp-b/transports": ^1.0.3
  "@mcp-b/extension-tools": ^0.2.2
  "@mcp-b/mcp-react-hooks": ^0.2.2

  # AI SDK packages
  ai: ^4.3.9
  "@ai-sdk/openai": ^1.3.16
  "@ai-sdk/anthropic": ^1.2.12
  "@assistant-ui/react-ai-sdk": ^0.10.14

  # Testing
  playwright: ^1.53.0
  "@playwright/test": ^1.53.0

  # Build tools (only used in shared/utils)
  tsup: ^8.4.0

onlyBuiltDependencies:
  - "@axodotdev/oranda"
  - "@tailwindcss/oxide"
  - dtrace-provider
  - esbuild
  - sharp
  - spawn-sync
  - unrs-resolver
  - workerd
